# Generated by Django 5.0.3 on 2024-03-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlagiarismApp', '0002_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.IntegerField(default='1'),
        ),
    ]
