# Generated by Django 5.0.3 on 2024-03-28 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlagiarismApp', '0005_alter_plagiarismreport_similarity_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plagiarismreport',
            name='current_submission_id',
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='submission',
            field=models.ForeignKey(default='445ec968-48a5-4c03-abf5-170277ac02df', on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_reports', to='PlagiarismApp.submission'),
            preserve_default=False,
        ),
    ]
