# Generated by Django 5.0.3 on 2024-03-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlagiarismApp', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='plagiarism_checker',
            field=models.BooleanField(default=True),
        ),
    ]
