# Generated by Django 5.0.3 on 2024-03-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlagiarismApp', '0008_assignment_plagiarism_checker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='receipient',
            new_name='recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new', 'New'), ('returned', 'Returned'), ('callback', 'Callback')], default='new', max_length=8),
            preserve_default=False,
        ),
    ]
