# Generated by Django 5.0.3 on 2024-03-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlagiarismApp', '0009_rename_receipient_notification_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='level',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('green', 'Green'), ('red', 'Red')], max_length=5),
        ),
    ]
